# Dockerfile - this is a comment. Delete me if you want.
#FROM python:2.7
FROM alpine:3.7
RUN apk add --no-cache python3-dev \
   && pip3 install --upgrade pip

COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt

EXPOSE 8080
ENTRYPOINT ["python"]
CMD ["app.py"]
